# This file is intentionally left blank.
# Its presence forces GitHub Pages to use Jekyll processing,
# which is necessary for serving single HTML files correctly
# when no other configuration is present.
